version: 2
services:
  backend:
    source: backend
    build:
      commands:
        - npm install
    start:
      command: npm start
    variables:
      NODE_ENV: production
      PORT: ${{ PORT }}